//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingProject {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class ITesting : global::System.Configuration.ApplicationSettingsBase {
        
        private static ITesting defaultInstance = ((ITesting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ITesting())));
        
        public static ITesting Default {
            get {
                return defaultInstance;
            }
        }
    }
}
